version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: demo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql_employees
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    command: --local-infile=1 --secure-file-priv=/docker-entrypoint-initdb.d
    volumes:
      - ../scripts/sample_data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - demo-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  tomcat:
    image: tomcat:9.0-jdk11
    container_name: demo_tomcat
    ports:
      - "8081:8080"
    volumes:
      - ./target/ROOT:/usr/local/tomcat/webapps/ROOT
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - CADP_KEY_MANAGER_HOST=${CADP_KEY_MANAGER_HOST}
      - CADP_KEY_MANAGER_PORT=${CADP_KEY_MANAGER_PORT}
      - CADP_REGISTRATION_TOKEN=${CADP_REGISTRATION_TOKEN}
      - CADP_PROTECTION_POLICY_NAME=${CADP_PROTECTION_POLICY_NAME}
      - CADP_USER_NAME=${CADP_USER_NAME}
      - CRDP_ENDPOINT=${CRDP_ENDPOINT}
      - CRDP_TLS=${CRDP_TLS}
      - CRDP_POLICY=${CRDP_POLICY}
      - CRDP_USER_NAME=${CRDP_USER_NAME}
      - CRDP_JWT=${CRDP_JWT}
    networks:
      - demo-net

  vault:
    image: hashicorp/vault:latest
    container_name: demo_vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: roottoken
      VAULT_ADDR: 'http://0.0.0.0:8200'
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
